CREATE TABLE pisos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    codigo_rede VARCHAR(100),
    codigo_loja VARCHAR(100) NOT NULL,
    largura NUMERIC(18, 6),
    altura NUMERIC(18, 6),
    rejunte NUMERIC(18, 6),
    pecas_por_caixa NUMERIC(18, 6),
    m2_por_caixa NUMERIC(18, 6) NOT NULL,
    local_de_uso VARCHAR(100),
    tipo_piso VARCHAR(100),
    pei INTEGER,
    retificado BOOLEAN,
    link_site VARCHAR(2048),
    link_foto VARCHAR(2048),
    valor NUMERIC(18, 6),
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE,
    versao BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pisos_m2_por_caixa_positivo CHECK (m2_por_caixa > 0),
    CONSTRAINT pisos_largura_positiva CHECK (largura IS NULL OR largura > 0),
    CONSTRAINT pisos_altura_positiva CHECK (altura IS NULL OR altura > 0),
    CONSTRAINT pisos_rejunte_nao_negativo CHECK (rejunte IS NULL OR rejunte >= 0),
    CONSTRAINT pisos_pecas_por_caixa_positiva CHECK (pecas_por_caixa IS NULL OR pecas_por_caixa > 0),
    CONSTRAINT pisos_pei_valido CHECK (pei IS NULL OR pei BETWEEN 1 AND 5),
    CONSTRAINT pisos_valor_nao_negativo CHECK (valor IS NULL OR valor >= 0)
);

CREATE INDEX pisos_codigo_loja_idx ON pisos (codigo_loja);
CREATE INDEX pisos_codigo_rede_idx ON pisos (codigo_rede);
CREATE INDEX pisos_tipo_piso_idx ON pisos (tipo_piso);
CREATE INDEX pisos_local_de_uso_idx ON pisos (local_de_uso);

CREATE TABLE atividades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(50) NOT NULL,
    descricao VARCHAR(500) NOT NULL,
    piso_nome VARCHAR(200),
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX atividades_tipo_idx ON atividades (tipo);
CREATE INDEX atividades_criado_em_idx ON atividades (criado_em DESC, id DESC);

INSERT INTO pisos (
    nome,
    codigo_rede,
    codigo_loja,
    largura,
    altura,
    rejunte,
    pecas_por_caixa,
    m2_por_caixa,
    local_de_uso,
    tipo_piso,
    pei,
    retificado,
    valor
)
VALUES
    (
        'Portinari Cimento Bold',
        'PTC-001',
        'L-001',
        60.000000,
        60.000000,
        2.000000,
        4.000000,
        1.440000,
        'Interno',
        'Porcelanato',
        4,
        TRUE,
        89.900000
    ),
    (
        'Elizeu Rustic Bege',
        'ELZ-002',
        'L-002',
        45.000000,
        45.000000,
        3.000000,
        6.000000,
        1.215000,
        'Externo',
        'Cerâmica',
        3,
        FALSE,
        42.500000
    );

INSERT INTO atividades (tipo, descricao, piso_nome, criado_em)
VALUES
    (
        'cadastro',
        'Piso Portinari Cimento Bold cadastrado',
        'Portinari Cimento Bold',
        CURRENT_TIMESTAMP - INTERVAL '1 hour'
    ),
    (
        'cadastro',
        'Piso Elizeu Rustic Bege cadastrado',
        'Elizeu Rustic Bege',
        CURRENT_TIMESTAMP - INTERVAL '30 minutes'
    );
