spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

redeasso:
  auth:
    local:
      enabled: ${REDEASSO_LOCAL_ADMIN_ENABLED:false}

server:
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE:true}
